class PathsManager:

    WIZZ_AIR = 'wizz-air'

    RYANAIR = 'ryanair'

    LUFTHANSA = 'lufthansa'

    LIST_OF_AIRLINES = [LUFTHANSA,RYANAIR,WIZZ_AIR]

    PROJECT_ROOT_DIR = 'C:\\Users\\macie\\Documents\\TextMiningProject\\matthausITberatung\\output_files\\'

    DOWNLOADED_FILES_DIR = PROJECT_ROOT_DIR + 'downloaded_files'

    CLEANED_DATA_FILES_DIR = PROJECT_ROOT_DIR + 'cleaned_data_files'

    PICKLED_FILES = PROJECT_ROOT_DIR + 'pickled_files'

    MAIN_OPINIONS_CORPUS_WITHOUT_STOPWORDS = 'MAIN_OPINIONS_CORPUS_WITHOUT_STOPWORDS'
    UNION_STOP_WORDS = 'UNION_STOP_WORDS'
    AIRLINES_DICT_OF_COUNTED_WORDS_COUNTER = 'AIRLINES_DICT_OF_COUNTED_WORDS_COUNTER'
    MAIN_OPINIONS_TDM = 'MAIN_OPINIONS_TDM'
    SUMMARY_TABLE = 'SUMMARY_TABLE'
    DICT_LIST_OF_BIGRAMS = 'DICT_LIST_OF_BIGRAMS'
    DICT_OF_COUNTERS_FROM_BIGRAMS = 'DICT_OF_COUNTERS_FROM_BIGRAMS'
    DATA_DICT_WITHOUT_STOP_WORDS = 'DATA_DICT_WITHOUT_STOP_WORDS'
    STOP_WORDS_LIST_FROM_SHORT_WORDS = 'STOP_WORDS_LIST_FROM_SHORT_WORDS'
    POTENTIAL_STOP_WORDS_LIST = 'POTENTIAL_STOP_WORDS_LIST'
    DICT_OF_AIRLINES_DATE_COUNTERS = 'DICT_OF_AIRLINES_DATE_COUNTERS'
    DICT_OF_LISTS_OF_DATE_AND_STRING_IN_YEAR = 'DICT_OF_LISTS_OF_DATE_AND_STRING_IN_YEAR'